// constants/productConstants.js

export const GET_PRODUCTS_BY_BRAND_REQUEST = 'GET_PRODUCTS_BY_BRAND_REQUEST';
export const GET_PRODUCTS_BY_BRAND_SUCCESS = 'GET_PRODUCTS_BY_BRAND_SUCCESS';
export const GET_PRODUCTS_BY_BRAND_FAIL = 'GET_PRODUCTS_BY_BRAND_FAIL';
